# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='notes_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Notes'),
        ),
    ]
