# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160315_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.LastName'),
            preserve_default=False,
        ),
    ]
